import type { Metadata } from "next";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCalendarCheck, faCheckCircle } from "@fortawesome/free-solid-svg-icons";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { notFound } from "next/navigation";

type Slug = "computer-phone-repair"|"smart-home-installation"|"it-support-small-business"|"website-social-media-management";

const services: Record<Slug,{title:string;cat:string;hero:string;desc:string;includes:string[];pricing:{name:string;price:string;features:string[]}[];faqs:{q:string;a:string}[]}> = {
  "computer-phone-repair":{title:"Computer & Phone Repair",cat:"Repair & Installation",hero:"/images/services/computer-phone-repair.svg",desc:"Fast, reliable repair for laptops, desktops, phones, and tablets. In-shop drop-off or we come to you — most repairs completed same-day.",
    includes:["Screen replacement","Battery replacement","Virus/malware removal","Data recovery","Hardware diagnostics","OS reinstall","Liquid damage assessment","Free estimate"],pricing:[{name:"Diagnostic",price:"Free",features:["Full hardware test","Verbal estimate","No obligation"]},{name:"Screen Repair",price:"$89–$249",features:["Phone/laptop/tablet","Same-day on most","90-day warranty"]},{name:"Virus Removal",price:"$79",features:["Full system scan","Malware cleanup","Performance tune-up"]}],faqs:[{q:"How long does a repair take?","a":"Most repairs are same-day. Complex repairs (data recovery, liquid damage) may take 2-3 days."},{q:"Do you offer a warranty?","a":"90-day warranty on all parts and labor. Manufacturer warranties honored."}]},
  "smart-home-installation":{title:"Smart Home Installation",cat:"Repair & Installation",hero:"/images/services/smart-home-installation.svg",desc:"Professional setup and integration of smart home devices — cameras, doorbells, thermostats, smart locks, speakers, and full-home automation systems.",
    includes:["Device mounting & wiring","App setup & configuration","Voice assistant integration","Network optimization","Scene & routine creation","Security system setup","User training","Post-install support"],pricing:[{name:"Single Device",price:"$79/device",features:["Mounting & wiring","App setup","Voice integration"]},{name:"3-Device Bundle",price:"$199",features:["3 devices installed","Full integration","Training included"]},{name:"Full Home Setup",price:"$499+",features:["Up to 10 devices","Network optimization","Custom routines"]}],faqs:[{q:"Do I need to buy the devices?","a":"We'll recommend devices but you purchase them. We handle 100% of the installation and configuration."},{q:"Can you integrate different brands?","a":"Yes — Nest, Ring, Ecobee, August, Sonos, Philips Hue, and all major platforms."}]},
  "it-support-small-business":{title:"IT Support for Small Business",cat:"Business IT & Digital Growth",hero:"/images/services/it-support.svg",desc:"Managed IT services for businesses with 1–50 employees. Network setup, cybersecurity, cloud migration, helpdesk support, and proactive monitoring — all for a flat monthly fee.",
    includes:["24/7 helpdesk support","Network setup & monitoring","Cybersecurity protection","Cloud migration & management","Email & productivity suite","Data backup & recovery","Hardware procurement","Quarterly IT reviews"],pricing:[{name:"Basic",price:"$299/mo",features:["Up to 5 devices","Remote support","Email security"]},{name:"Pro",price:"$599/mo",features:["Up to 20 devices","On-site visits","Cybersecurity suite"]},{name:"Enterprise",price:"$1,199/mo",features:["Unlimited devices","24/7 priority","vCIO consulting"]}],faqs:[{q:"Is there a contract?","a":"Month-to-month. No long-term commitment. Cancel anytime with 30 days notice."},{q:"What's your response time?","a":"Under 1 hour for critical issues, under 4 hours for standard tickets during business hours."}]},
  "website-social-media-management":{title:"Website & Social Media Management",cat:"Business IT & Digital Growth",hero:"/images/services/website-social-media.svg",desc:"Custom websites, SEO, and social media management for local businesses. We build your online presence and drive real customers through your doors.",
    includes:["Custom website design","SEO optimization","Social media strategy","Content creation (posts/graphics)","Monthly analytics reports","Google Business Profile management","Ad campaign management","E-commerce integration"],pricing:[{name:"Starter",price:"$399/mo",features:["5-page website","Basic SEO","2 social platforms"]},{name:"Growth",price:"$799/mo",features:["10-page website","Advanced SEO","4 social platforms","Blog content"]},{name:"Premium",price:"$1,499/mo",features:["Custom web app","Full SEO suite","All platforms","Ad management"]}],faqs:[{q:"How long until my website is live?","a":"Typically 2-4 weeks for a standard site. E-commerce and custom apps may take 6-8 weeks."},{q:"Do you write the content?","a":"Yes! We provide copywriting and professional photography coordination as part of all plans."}]},
};

export function generateStaticParams(){return Object.keys(services).map(s=>({slug:s}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const s=services[slug as Slug];return s?{title:s.title}:{title:"Not Found"};}

export default async function ServiceDetailPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const s=services[slug as Slug];if(!s)notFound();
  return (<>
    <section className="relative overflow-hidden bg-gradient-to-r from-indigo-800 to-cyan-600 text-white"><div className="absolute inset-0 bg-cover bg-center opacity-15" style={{backgroundImage:`url(${s.hero})`}}/><div className="relative mx-auto max-w-7xl px-4 py-16 sm:py-20 sm:px-6 lg:px-8"><Badge className="mb-3 bg-white/10 text-white border-white/20">{s.cat}</Badge><h1 className="text-4xl sm:text-5xl font-extrabold mb-4">{s.title}</h1><p className="text-white/80 text-lg max-w-xl">{s.desc}</p><div className="mt-6"><Link href="/booking"><Button size="lg" className="bg-lime-500 hover:bg-lime-600 text-slate-900 font-bold"><FontAwesomeIcon icon={faCalendarCheck} className="mr-2 size-4"/>Book This Service</Button></Link></div></div></section>
    <section className="py-16 bg-white dark:bg-slate-900"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-3"><div className="lg:col-span-2"><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">What&apos;s Included</h2><div className="grid sm:grid-cols-2 gap-3 mb-10">{s.includes.map(i=>(<div key={i} className="flex items-start gap-2"><FontAwesomeIcon icon={faCheckCircle} className="size-4 text-cyan-500 mt-0.5 shrink-0"/><span className="text-slate-600 dark:text-slate-300">{i}</span></div>))}</div><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">FAQ</h2><div className="space-y-3">{s.faqs.map(f=>(<details key={f.q} className="border border-indigo-100 dark:border-slate-700 rounded-lg p-4 group"><summary className="font-medium text-slate-800 dark:text-slate-200 cursor-pointer list-none flex justify-between items-center"><span>{f.q}</span><span className="text-indigo-500 dark:text-cyan-400 group-open:hidden">+</span><span className="text-indigo-500 dark:text-cyan-400 hidden group-open:inline">−</span></summary><p className="mt-3 text-slate-500 dark:text-slate-400 text-sm leading-relaxed">{f.a}</p></details>))}</div></div><div><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Pricing</h2><div className="space-y-4">{s.pricing.map(p=>(<Card key={p.name} className="glass border-0 dark:bg-slate-900/75"><CardContent className="p-5"><h3 className="font-bold text-slate-900 dark:text-white">{p.name}</h3><p className="text-2xl font-extrabold text-indigo-600 dark:text-cyan-400 my-1">{p.price}</p><ul className="mt-3 space-y-1">{p.features.map(f=><li key={f} className="text-sm text-slate-500 dark:text-slate-400 flex items-start gap-2"><FontAwesomeIcon icon={faCheckCircle} className="size-3 text-cyan-500 mt-0.5 shrink-0"/>{f}</li>)}</ul></CardContent></Card>))}</div><div className="mt-6"><Link href="/booking"><Button className="w-full bg-indigo-700 hover:bg-indigo-800 dark:bg-indigo-600">Book Now</Button></Link></div></div></div></div></section>
  </>);
}
