import type { Metadata } from "next";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faShield, faBolt, faCertificate } from "@fortawesome/free-solid-svg-icons";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "About Us" };

export default function AboutPage(){return (<><section className="bg-gradient-to-r from-indigo-800 to-cyan-600 text-white py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h1 className="text-4xl font-extrabold mb-3">About TechServe Pro</h1><p className="text-indigo-200 text-lg">Your local tech partner since 2016 — certified, reliable, and genuinely helpful.</p></div></section><section className="py-16 bg-white dark:bg-slate-900"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 items-center"><div><h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-4">Our Story</h2><p className="text-slate-500 dark:text-slate-400 leading-relaxed mb-4">TechServe Pro was founded in 2016 by Alex Chen, a CompTIA-certified IT professional who was tired of seeing local businesses overpay for subpar tech support and homeowners struggling with confusing smart home setups.</p><p className="text-slate-500 dark:text-slate-400 leading-relaxed">Today, our team of 15 certified technicians serves 150+ business clients and thousands of residential customers. We&apos;re CompTIA, Google, Meta, and major smart home platform certified.</p></div><img src="/images/about/about-hero.jpg" alt="About" className="rounded-2xl shadow-lg w-full object-cover aspect-video"/></div></div></section><section className="py-16 bg-slate-50 dark:bg-slate-950"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-slate-900 dark:text-white text-center mb-12">Our Values</h2><div className="grid gap-8 sm:grid-cols-3">{[{icon:faShield,title:"Trust & Security",desc:"Your data and privacy come first. Every tech is background-checked and follows strict security protocols."},{icon:faBolt,title:"Speed",desc:"Average response time under 4 hours. We know downtime costs money."},{icon:faCertificate,title:"Expertise",desc:"CompTIA, Google, Meta, and platform-certified. Ongoing training is non-negotiable."}].map(v=>(<div key={v.title} className="text-center p-6 glass rounded-xl dark:bg-slate-900/75"><div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 mb-4"><FontAwesomeIcon icon={v.icon} className="size-6"/></div><h3 className="font-bold text-slate-900 dark:text-white mb-2">{v.title}</h3><p className="text-sm text-slate-500 dark:text-slate-400">{v.desc}</p></div>))}</div><div className="text-center mt-12"><Link href="/booking"><Button size="lg" className="bg-indigo-700 hover:bg-indigo-800 dark:bg-indigo-600">Book a Tech</Button></Link></div></div></section></>);}
