import type { Metadata } from "next";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPhone, faEnvelope, faLocationDot, faClock } from "@fortawesome/free-solid-svg-icons";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export const metadata: Metadata = { title: "Contact Us" };

export default function ContactPage(){return (<><section className="bg-gradient-to-r from-indigo-800 to-cyan-600 text-white py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h1 className="text-4xl font-extrabold mb-3">Contact Us</h1><p className="text-indigo-200 text-lg">We&apos;re here to help. Reach out anytime.</p></div></section><section className="py-16 bg-slate-50 dark:bg-slate-950"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-3"><div className="space-y-6">{[{icon:faPhone,label:"Phone",val:"(555) 123-TECH"},{icon:faEnvelope,label:"Email",val:"hello@techservepro.com"},{icon:faLocationDot,label:"Service Area",val:"Metro Area — On-Site & Remote"},{icon:faClock,label:"Hours",val:"Mon-Fri 8AM-8PM · Sat 9AM-5PM"}].map(c=>(<div key={c.label} className="flex items-start gap-3"><div className="w-10 h-10 rounded-full bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center shrink-0"><FontAwesomeIcon icon={c.icon} className="size-4"/></div><div><h3 className="font-semibold text-slate-900 dark:text-white text-sm">{c.label}</h3><p className="text-slate-500 dark:text-slate-400 text-sm">{c.val}</p></div></div>))}</div><div className="lg:col-span-2 glass rounded-2xl p-6 sm:p-8 dark:bg-slate-900/75"><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Send Us a Message</h2><form action="/api/contact" method="POST" className="space-y-4"><div className="grid sm:grid-cols-2 gap-4"><div><Label>Name</Label><Input name="name" required/></div><div><Label>Email</Label><Input name="email" type="email" required/></div></div><div><Label>Phone</Label><Input name="phone"/></div><div><Label>Message</Label><Textarea name="message" rows={4} required/></div><Button type="submit" className="bg-indigo-700 hover:bg-indigo-800 dark:bg-indigo-600">Send Message</Button></form></div></div></div></section></>);}
